### ISSUE TITLE
非常感谢作者！

### ISSUE THREAD

**Issue by 276562578** [523753042/wedding-marriage-fullstack#1]
这个项目部署起来难度不大，我是0基础小程序的，反而是腾讯的一些乱七八糟的东西一直在阻止我

有个问题请教下，如何打开评论呢？

**Comment by 523753042** [comment]
评论现在开启的话是不会通过审核的，所以需要绕过去。
具体代码在wedding-marriage-fullstack/wedding-weapp/miniprogram/pages/comment/index.wxml
`      <button wx:if="{{remarkList.length>45}}" class="btn border shadow" bindtap="showWanted">
`
35行，这里用了变量控制，你可以在数据库里面控制这个长度，审核的时候少塞点随机祝福。
等审核通过发布以后，再去数据库加数量给他显示出来。

**Comment by 276562578** [comment]
感谢，我找了一下午，以为有哪个地方有开关

**Comment by 276562578** [comment]
不过一直提示以下错误
```javascript
(in promise) MiniProgramError
"collection.get:fail -502005 database collection not exists. [ResourceNotFound] Db or Table not exist. Please check your request, but if the problem cannot be solved, contact us."
String(env: Windows,mp,1.06.2207210; lib: 2.11.3)
errorReport @ WAServiceMainContext.js:2
thirdErrorReport @ WAServiceMainContext.js:2
(anonymous) @ WAServiceMainContext.js:2
u @ WASubContext.js?t=wechat&s=1659185073556&v=2.11.3:2
h @ WASubContext.js?t=wechat&s=1659185073556&v=2.11.3:2
(anonymous) @ WASubContext.js?t=wechat&s=1659185073556&v=2.11.3:2
value @ WASubContext.js?t=wechat&s=1659185073556&v=2.11.3:2
o @ WASubContext.js?t=wechat&s=1659185073556&v=2.11.3:2
(anonymous) @ WASubContext.js?t=wechat&s=1659185073556&v=2.11.3:2
```

**Comment by 276562578** [comment]
难道意思是先通过几条展示，但这个时候不显示按钮，之后审核通过后再加几条让按钮显示出来？

**Comment by 523753042** [comment]
你要手动去数据库创建一下对应的database

**Comment by 276562578** [comment]
ok，搞清楚了，添加remark的collection

**Comment by 276562578** [comment]
可能是我太菜了，感觉打通评论好复杂，代码通过审核了，也在云数据库中添加了remark的collection
但是无论发什么都会返回敏感词，再就是每次进入页面会提示

```javascript
WAServiceMainContext.js:2 (in promise) MiniProgramError
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at http://127.0.0.1:18842/appservice/pages/comment/index.js:70:15(env: Windows,mp,1.06.2207210; lib: 2.11.3)
```

大佬能请教一下吗

**Comment by 276562578** [comment]
然后我没看懂，祝福到底是在remark还是在comment

大佬能出个开通评论的指南吗？谢谢啦

**Comment by 523753042** [comment]
****
<img width="865" alt="image" src="https://user-images.githubusercontent.com/26767055/182059373-73557389-6d66-410d-9b5f-7c266a0cb832.png">

**Comment by 276562578** [comment]
我尝试了手动添加remark的内容，但仍然报错

我打算重建一次，开启评论步骤如下：

1. 调整`wedding-marriage-fullstack/wedding-weapp/miniprogram/pages/comment/index.wxml`中的45 为5
2. 创建remark这个collection
3. 提交代码审核
4. 在remark中手动创建6个记录

之后我再有什么问题我再来

感觉字词审核还有这个可能会出问题

> 可能是我太菜了，感觉打通评论好复杂，代码通过审核了，也在云数据库中添加了remark的collection 但是无论发什么都会返回敏感词，再就是每次进入页面会提示
> 
> ```js
> WAServiceMainContext.js:2 (in promise) MiniProgramError
> Cannot read property 'length' of undefined
> TypeError: Cannot read property 'length' of undefined
>     at http://127.0.0.1:18842/appservice/pages/comment/index.js:70:15(env: Windows,mp,1.06.2207210; lib: 2.11.3)
> ```
> 
> 大佬能请教一下吗

**Comment by 276562578** [comment]
这里是`miniprogram/pages/comment/index.wxml`
```javascript
     <view wx:if="{{remarkList.length>3}}">
        <view class="btn border shadow" wx:if="{{userInfo}}" bindtap="showLayer">{{zhufu}}</view>
        <button open-type="getUserInfo" wx:else hover-class="none" class="btn border shadow" bindgetuserinfo="getUserInfo" data-type="1" lang="zh_CN">
          {{zhufu}}
        </button>
      </view>
```
这里是云数据库
![image](https://user-images.githubusercontent.com/11238775/186618416-a9e3e1a6-31de-48f4-bf2f-28f2d258752e.png)
打开祝福页面报错
```javascript
WAServiceMainContext.js:2 (in promise) MiniProgramError
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at http://127.0.0.1:62718/appservice/pages/comment/index.js:70:15(env: Windows,mp,1.06.2207210; lib: 2.11.3)
```

**Comment by 523753042** [comment]
建议你还是把那个判断改成时间戳判断吧，简单一点。保证审核时候不显示就行

**Comment by 276562578** [comment]
啊这，所以是那个判断有问题么QAQ，按理说没问题啊，我看他定位到`res.length`这里报的错

**Comment by 523753042** [comment]
这个就考验你debuger的能力了，爱莫能助了
