### ISSUE TITLE
node-v16.x 安装 wedding-nest-server 依赖报错

### ISSUE THREAD

**Issue by 948764321** [523753042/wedding-marriage-fullstack#2]
node 16.x 版本安装会报错

不过可以用 node 14.x 安装

![image](https://github.com/523753042/wedding-marriage-fullstack/assets/74353117/8e60f182-9090-4251-b0ac-323a30a0015d)

**Comment by 523753042** [comment]
回复晚了。
方法是对的，是之前基于node14版本开发的。稳定启动后暂时没有更新
